apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: local-host-pv
    meta.helm.sh/release-namespace: default
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2021-10-26T18:22:08Z"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: test-pvc
  namespace: default
  resourceVersion: "32309751"
  uid: cf0560f4-3a25-4cdc-b1ab-8fd1d4d9f47e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  volumeMode: Filesystem
  volumeName: test-pv

