apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.storage_size }}
  claimRef:
    name: {{ .Values.name }}-pvc
    namespace: {{ .Values.namespace}}
  hostPath:
    path: {{ .Values.host_path }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
