apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.access_mode}}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.storage_size }}
  volumeMode: Filesystem
  volumeName: {{.Values.name}}-pv

